### ISSUE TITLE
Cannot evaluate return value from shared library

### ISSUE THREAD

**Issue by kstutz** [homeaway/jenkins-spock#112]
Expected Behavior
==============================

When I have a shared library in my vars folder like this:
```
def call() {
  def a = 3
  return a
}
```

... and I try to check the return value in a test using Jenkins-Spock like this:
```
def "example test"() {
  when:
  def result = scriptUnderTest.call()
  then:
  result == 3
}
```

...I would expect the test to succeed because the result is 3.

Actual Behavior
==============================

The test fails because I get 'null' as the result. When debugging, I see that the value is calculated in the code correctly, I just cannot access it in the test.

Steps to Reproduce
==============================

1. Create a shared library in your vars folder that uses a return statement at the end.
2. Try to check the returned value in a test using Jenkins-Spock.

Additional Information
==============================

I have written quite some tests with Jenkins-Spock already and really love it. But up until now, I have only worked on a project that did not use return values in vars scripts. Is it possible to check them? What am I missing here?

**Comment by EnsuingRequiem** [comment]
Have you used the `loadPipelineScriptForTest` method to load the script itself?
I've had no troubles with test as (using your global variable assumption):
```
def "Should return something"() {
  given: 'Global variable is defined'
  def newGlobalVariable = loadPipelineScriptForTest('vars/newGlobalVariable.groovy')
  when: 'The variable is used'
  def returnedValue = newGlobalVariable()
  then:
  returnedValue == 3
}
```

**Comment by kstutz** [comment]
Oh dear, yes, you are right.
The problem was an enclosing pipeline step. When I move the return statement out of this step, it works fine.
Sorry for not checking it properly myself!
